### ISSUE TITLE
Multiple matches in body

### ISSUE THREAD

**Issue by bwoestman** [donhenton/mountebank-UI#1]
I would like to be able to send a request to set up an imposter with more than one match in the body.  I was able to accomplish this by sending a json POST directly to Mountebank but couldn't get multiple matches using the UI.  Is this possible?  I forked this repo to add the additional feature if it's not already implemented.

Thanks,
Brian

**Comment by donhenton** [comment]
Very cool, I think that the way I would have done this was cop out with javascript, but it should be interesting to see what you have in mind!

**Comment by woestmab** [comment]
I will give it a shot and let you know when I have something worth sharing.  Thanks!
