### ISSUE TITLE
How to deploy mountebank

### ISSUE THREAD

**Issue by sai-tirunagiri** [donhenton/mountebank-UI#6]
Hi,

I have been working on getting this mountebank-UI deployed on http-server. But, I have some challenges of not being deployed. 

Could someone please instruct me on how to deploy this on any webserver.

Thank you,
Sai

**Comment by donhenton** [comment]
The application can be deployed on any app server, for example its on gh-pages, at http://donhenton.github.io/mountebank-UI/public_html/index.html. The gulp task 'build' should produce a copy of the file and resources ready to run. Compare that output to the contents of the gh-pages branch of this app. gh-pages is what runs at the url above HTH
